[package]
name = "ffi"
version = "0.1.0"
authors = ["Ian Douglas Scott <idscott@system76.com>"]
edition = "2018"

[lib]
name = "system76_keyboard_configurator"
crate-type = [ "cdylib" ]

[dependencies]
glib = "0.10"
gtk-sys = "0.10"
gtk = "0.9"
system76-keyboard-configurator = { path = "../" }
