on: [push, pull_request]

name: ci

jobs:
  windows-mingw32:
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        install: mingw-w64-i686-gtk3 mingw-w64-i686-toolchain mingw-w64-i686-ntldd mingw-w64-i686-imagemagick
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-i686-pc-windows-gnu
    - uses: actions/checkout@v2
    - name: Build and package
      shell: msys2 {0}
      run: |
        cd windows
        sed -i 's|RUSTUP =.*$|RUSTUP = \"C:/Rust/.cargo/bin/rustup.exe\"|' build.py
        python build.py --debug
    - uses: actions/upload-artifact@v2
      with:
        if-no-files-found: error
        name: keyboard-configurator-mingw32-${{ github.sha }}
        path: |
          windows/keyboard-configurator.msi
          windows/out/

  macos:
    runs-on: macos-latest
    steps:
    - run: brew install gtk+3 makeicns imagemagick
    - run: npm install -g appdmg
    #- run: echo "::add-path::$HOME/.new_local/bin"
    #- run: |
    #    curl https://gitlab.gnome.org/GNOME/gtk-osx/raw/master/gtk-osx-setup.sh | sh
    #    jhbuild bootstrap-gtk-osx
    #    jhbuild build meta-gtk-osx-bootstrap meta-gtk-osx-gtk3
    - run: cd && git clone https://gitlab.gnome.org/GNOME/gtk-mac-bundler && make -C gtk-mac-bundler install
    - run: echo "::add-path::$HOME/.local/bin"
    - uses: actions/checkout@v2
    - run: cargo build --examples
    - run: cd macos && ./package.sh
    - run: plutil macos/Info.plist
    - uses: actions/upload-artifact@v2
      with:
        if-no-files-found: error
        name: keyboard-configurator-macos-${{ github.sha }}
        path: |
          macos/keyboard-configurator.dmg
          macos/System76KeyboardConfigurator.app
